const cars = [
  {
    id: 1,
    name: "BMW X2",
    year: 2021,
    city: "Moskva",
    fuel: "2,3 l/benzin",
    power: "317 l.s.",
    price: 7150,
    currency: "rub/sut",
    category: "boshlang`ich",
    img: "./img/BMW X2, 2021.svg",
  },
  {
    id: 2,
    name: "Kia Sportage",
    year: 2022,
    city: "Dubay",
    fuel: "2,3 l/benzin",
    power: "317 l.s.",
    price: 7150,
    currency: "rub/sut",
    category: "Qulay",
    img: "./img/Kia Sportage, 2022.svg",
  },
  {
    id: 3,
    name: "Lexus IS",
    year: 2018,
    city: "Moskva",
    fuel: "2,3 l/benzin",
    power: "317 l.s.",
    price: 7150,
    currency: "rub/sut",
    category: "Biznes",
    img: "./img/Lexus IS, 2018.svg",
  },
  {
    id: 4,
    name: "Jaguar XF",
    year: 2012,
    city: "Dubay",
    fuel: "2,3 l/benzin",
    power: "317 l.s.",
    price: 7150,
    currency: "rub/sut",
    category: "Biznes",
    img: "./img/Jaguar XF,  2012.svg",
  },
  {
    id: 5,
    name: "Toyota RAV4",
    year: 2017,
    city: "Dubay",
    fuel: "2,3 l/benzin",
    power: "317 l.s.",
    price: 7150,
    currency: "rub/sut",
    category: "boshlang`ich",
    img: "./img/Toyota RAV4,  2017.svg",
  },
  {
    id: 6,
    name: "Mazda 6",
    year: 2021,
    city: "Moskva",
    fuel: "2,3 l/benzin",
    power: "317 l.s.",
    price: 7150,
    currency: "rub/sut",
    category: "Qulay",
    img: "./img/2021 Mazda 6, 2021.svg",
  },
  // {
  //   id: 7,
  //   name: "Kia Sportage",
  //   year: 2022,
  //   city: "Moskva",
  //   fuel: "2,3 l/benzin",
  //   power: "317 l.s.",
  //   price: 7150,
  //   currency: "rub/sut",
  //   category: "Qulay",
  //   img: "./img/Kia Sportage, 2022.svg",
  // },
  // {
  //   id: 8,
  //   name: "Lexus IS",
  //   year: 2018,
  //   city: "Moskva",
  //   fuel: "2,3 l/benzin",
  //   power: "317 l.s.",
  //   price: 7150,
  //   currency: "rub/sut",
  //   category: "Biznes",
  //   img: "./img/Lexus IS, 2018.svg",
  // },
  // {
  //   id: 9,
  //   name: "BMW X2",
  //   year: 2021,
  //   city: "Moskva",
  //   fuel: "2,3 l/benzin",
  //   power: "317 l.s.",
  //   price: 7150,
  //   currency: "rub/sut",
  //   category: "Premium",
  //   img: "./img/BMW X2, 2021.svg",
  // },
];
